name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install .NET 5
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.101
      - name: Build & test
      - run: dotnet build --configuration Release --no-restore
      - run: dotnet test --configuration Release --logger GitHubActions
